# Generated by Django 5.2 on 2025-04-23 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='due_date',
            new_name='end_date',
        ),
    ]
