# Generated by Django 5.2 on 2025-06-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyprogress',
            name='documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
