# Generated by Django 5.2 on 2025-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_weeklyprogress_week_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutesofmeeting',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
