# Generated by Django 5.2 on 2025-05-14 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('progress', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('At Risk', 'At Risk'), ('On Track', 'On Track')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to='tracker.project')),
            ],
        ),
    ]
