# Generated by Django 5.2 on 2025-05-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_weeklyprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogress',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
