# Generated by Django 5.2 on 2025-05-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_weeklyprogress_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogress',
            name='status',
            field=models.CharField(choices=[('At Risk', 'At Risk'), ('On Track', 'On Track'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
