# Generated by Django 5.2 on 2025-05-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_weeklyprogress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogress',
            name='status',
            field=models.CharField(choices=[('At Risk', 'At Risk'), ('On Track', 'On Track')], max_length=20),
        ),
    ]
